#!/bin/sh
# Pass battery name -in /sys/class/power_supply as fst argument

for x in "$(xrdb -query | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 75 ]; then
    color="$color11"
elif [ "$capacity" -ge 50 ]; then
    color="$color10"
elif [ "$capacity" -ge 25 ]; then
    color="$color9"
else
    color="$color1"
    warn=" "
fi

[ -z $warn ] && warn=""

[ "$status" = "Charging" ] && color="$color4"

msg="$(echo "$status$warn$capacity" | sed -e 's/,//g;s/Discharging/  /;s/Not charging/ /g;s/Unknown/  /g;s/Full/ /g;s/ 0*/ /g;s/ :/ /g;s/$/%/g')"
# printf "<span color='%s'>%s%s%s</span>" "$color" "$(echo "$status" | sed -e "s/,//g;s/Discharging/  /;s/Charging/ /g;s/Unknown/  /g;s/Full/ /g;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/g')"
echo "$msg"
