#!/usr/bin/sh

for x in "$(xrdb -query | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

# get color aliases
shopt -s expand_aliases
source ~/.bashrc

# Look for daily meteo report -> supposed to be run once or twice a day
meteo_report="$HOME/.local/share/meteo_report"
get_meteo() {
	curl --silent wttr.in > "$meteo_report" || exit 1;
}

show_meteo() {
	rain_proba=$(sed '16q;d' $meteo_report | grep -o "[0-9]*%" | sort -rn | sed '1q')
	min_max_temp=$(sed '13q;d' $meteo_report | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -rn | sed -e 1b -e '$!d' | tr "\n|m" " " | awk '{print " ~ ❄ " $2 " ☼ " $1}')
	min_temp=$(sed '13q;d' $meteo_report | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -rn | tail -n 1 | tr -d "m")
	max_temp=$(sed '13q;d' $meteo_report | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -rn | head -n 1 | tr -d "m")

	lblue="$color12"
	lcyan="$color14"
	lyellow="$color11"

	echo "<span size='large' color='${lblue}'><b>🌧️</b></span>$rain_proba <span size='large' color='${lcyan}'><big>❄</big></span>$min_temp°C <span size='large' color='${lyellow}'><big>☀</big></span>$max_temp°C"
}


# check if meteo report has been updated today.
[ "$(stat -c %y .local/share/meteo_report 2> /dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] || get_meteo

show_meteo
