#!/bin/sh

on_off=$(amixer sget Master | awk -F"[][]" '{print $6}' | sed '/^\s*$/d')
volume=$(amixer sget Master | awk -F"[][]" '/dB/ {print $2}' | sed 's/%//g')

if [ $on_off == "off" ]; then
    icon="🔇"
elif [ "$volume" -ge 66 ]; then
    icon="🔊"
elif [ "$volume" -ge 33 ]; then
    icon="🔉"
else
    icon="🔈"
fi

echo "$icon $volume%"
