[font]
size = 12.0

[font.bold]
family = "Literation Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Literation Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Literation Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Literation Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[colors.selection]
text = "0x1d1f21"
background = "0xffffff"

