#!/bin/sh
# Sets the background. Many scripts need to do this, but I've put it here so you can easily change all their actions.

wallpaper=$(find ${WALLPAPERS} -type f  | shuf -n1)

xwallpaper --center $wallpaper
